services:
  beltsecurity:
    build: .
    container_name: beltsecurity-web
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    name: mcgregory_appnet
    external: true
